export const blogTags = [
  "technology",
  "web development",
  "programming",
  "data science",
  "entrepreneurship",
  "productivity",
  "career development",
  "marketing",
  "personal finance",
  "lifestyle",
  "artificial intelligence",
  "cybersecurity",
  "blockchain",
  "cloud computing",
  "mobile development",
  "UI/UX design",
  "e-commerce",
  "social media",
  "content marketing",
  "seo",
];
